import localFont from "next/font/local";

import "@/styles/_theme.scss";
import "@/styles/_reset.scss";
import "@/styles/_common.scss";
import Header from "@/components/Header";
import DarkModeContextProvider from "@/context/DarkModeContext";

import styles from "./layout.module.scss";

import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const pretendard = localFont({
  src: "../../public/fonts/PretendardVariable.woff2",
  display: "swap",
  weight: "45 920",
});

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html>
      <body className={pretendard.className}>
        <main className={styles.container}>
          <div className={styles.layout}>
            <DarkModeContextProvider>
              <Header />
              {children}
            </DarkModeContextProvider>
          </div>
        </main>
      </body>
    </html>
  );
}
